apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: investment-chatbot
  template:
    metadata:
      labels:
        app: investment-chatbot
    spec:
      containers:
      - name: backend
        image: your-registry/investment-chatbot-backend:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: openai-key
          - name: PERPLEXITY_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: perplexity-key
          - name: REDIS_URL
            value: "redis://redis-service:6379"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: url
        ports:
        - containerPort: 8000
      - name: redis
        image: redis:7.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 6379