version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/investment_chatbot
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=investment_chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: